version: '3.8'
services:
  frontend:
    build: .
    container_name: frontend
    restart: always
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"